test:
  mysql41: 9307
production:
  pid_file: ~/asky/shared/tmp/pids/searchd.pid
  indices_location: ~/asky/shared/db/sphinx
  configuration_file: ~/asky/shared/config/production.sphinx.conf
  binlog_path: ~/asky/shared/binlog
